### ISSUE TITLE
Errors with interpolation in INI files

### ISSUE THREAD

**Issue by nightwatchcyber** [bkabrda/anymarkup-core#2]
I am seeing errors when interpolated strings are present in INI files as follows:

[foo]
spam = 1 [%%(test)s]
baz = 1.1
[[blah]]
blahblah = True, text4
nothing = None

Getting a "configobj.MissingInterpolationOption" error

**Comment by nightwatchcyber** [comment]
I am going to provide a pull request which adds an optional "interpolation" option which can be passed to configobj to disable this behavior. The pull request also includes tests.

**Comment by bkabrda** [comment]
Fixed in #3.
